//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionServicioAdicional
    {
        public int IdAtencion { get; set; }
        public Nullable<int> IdMascota { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual ServiciosAdicionale ServiciosAdicionale { get; set; }
    }
}
