//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cirugia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cirugia()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Mascota { get; set; }
        public Nullable<int> ID_ProductoProveedor { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ID_Sede { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
        public virtual Sede Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
    }
}
