//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public Nullable<int> ID_Mascota { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
        public Nullable<int> ID_Sede { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string TipoCita { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
