//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> ID_Mascota { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
        public Nullable<int> ID_Sede { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string TipoCita { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
