//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int ID { get; set; }
        public Nullable<int> ID_ProductosProveedor { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        [JsonIgnore]

        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
    }
}
