//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int ID { get; set; }
        public Nullable<int> ID_Factura { get; set; }
        public Nullable<int> ID_Cirugia { get; set; }
        public Nullable<int> ID_Hospitalizacion { get; set; }
        public Nullable<int> ID_ProductoFarmacia { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual Cirugia Cirugia { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Hospitalizacion Hospitalizacion { get; set; }
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
    }
}
