//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public int ID { get; set; }
        public Nullable<int> ID_Factura { get; set; }
        public Nullable<int> ID_Cirugia { get; set; }
        public Nullable<int> ID_Hospitalizacion { get; set; }
        public Nullable<int> ID_ProductoFarmacia { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<int> ID_ServicioAdicional { get; set; }
    
        public virtual Cirugia Cirugia { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Hospitalizacion Hospitalizacion { get; set; }
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
        public virtual ServiciosAdicionale ServiciosAdicionale { get; set; }
    }
}
