//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCompra
    {
        public int EntregaID { get; set; }
        public Nullable<int> OrdenCompraID { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Observaciones { get; set; }
    
        public virtual OrdenesCompra OrdenesCompra { get; set; }
    }
}
