//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFarmacia
    {
        public int IdInventario { get; set; }
        public int IdProductosFarmacia { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
    }
}
