//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Sede
    {
        public int ID { get; set; }
        public Nullable<int> ID_ProductoFamarcia { get; set; }
        public Nullable<int> ID_ProductoProveedor { get; set; }
        public Nullable<int> ID_Sede { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int Id_Inventario { get; set; }
    
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual InventarioFarmacia InventarioFarmacia { get; set; }
    }
}
