//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioSede
    {
        public int IdInventarioSede { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<int> IdProductosProveedor { get; set; }
        public int IdSede { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
