//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Sede
    {
        public int ID { get; set; }
        public Nullable<int> ID_ProductoFamarcia { get; set; }
        public Nullable<int> ID_ProductoProveedor { get; set; }
        public Nullable<int> ID_Sede { get; set; }
        public Nullable<int> Cantidad { get; set; }

        [JsonIgnore]
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
        [JsonIgnore]
        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
