//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioFarmacia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioFarmacia()
        {
            this.Inventario_Sede = new HashSet<Inventario_Sede>();
        }
    
        public int Id_Inventario { get; set; }
        public int Id_Medicamento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Unidad_Medida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Sede> Inventario_Sede { get; set; }
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
    }
}
