//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioSede
    {
        public int IdInventarioSede { get; set; }
        public Nullable<int> IdMedicamento { get; set; }
        public Nullable<int> IdProductosProveedor { get; set; }
        public int IdSede { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
        public virtual Productos_Proveedor Productos_Proveedor { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
