//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesCompra()
        {
            this.HistorialCompras = new HashSet<HistorialCompra>();
            this.OrdenesCompraDetalles = new HashSet<OrdenesCompraDetalle>();
        }
    
        public int IdCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMetodoPago { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual EstadosOrdenCompra EstadosOrdenCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCompra> HistorialCompras { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesCompraDetalle> OrdenesCompraDetalles { get; set; }
    }
}
