//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion
    {
        public int Id_Prescripcion { get; set; }
        public int Id_Paciente { get; set; }
        public int Id_Medicamento { get; set; }
        public int Id_Medico { get; set; }
        public System.DateTime Fecha_Prescripcion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
    }
}
