//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescripcion
    {
        public int Id_Prescripcion { get; set; }
        public int Id_Paciente { get; set; }
        public int Id_Medicamento { get; set; }
        public int Id_Medico { get; set; }
        public System.DateTime Fecha_Prescripcion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Productos_Farmacia Productos_Farmacia { get; set; }
    }
}
