//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServ.Models
{
    using System;
    using System.Collections.Generic;


    public partial class Servicios_Adicionales
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Costo { get; set; }

    }
}
